### ISSUE TITLE
BUG: Server Error 500

### ISSUE THREAD

**Issue by eblabs** [gis-ops/wordpress-markdown-git#11]
**Versions**
Wordpress: 5.3.1
Documents for Git: 0.1

**Describe the bug**
Getting an error message when viewing a page with the shortcode (see below).
500 - Server Error

The page can be accessed here:
https://eblabs.com/test-post/
pw: github

**Paste the shortcode and the censored contents of config.json**
[git-github-markdown url="https://raw.githubusercontent.com/eblabs/eblabs_community/master/docs/RetimeTools/README.md"]

```
{
  "limit": 5,
  "classes": "",
  "Github": {
    "user": "xxxxxx",
    "token": "xxxxxxxx"
  },
  "Bitbucket": {
    "user": "",
    "token": ""
  },
  "Gitlab": {
    "user": "",
    "token": ""
  }
}
```

Here is how I configured my token
![image](https://user-images.githubusercontent.com/5941510/77261213-427e8d80-6c8d-11ea-8334-73f0a79ba63b.png)

**Expected behavior**
I was expecting the md to display in the post.
https://github.com/eblabs/eblabs_community/blob/master/docs/RetimeTools/README.md

**Screenshots**

![image](https://user-images.githubusercontent.com/5941510/77261236-70fc6880-6c8d-11ea-908e-aa91408b68d0.png)

![image](https://user-images.githubusercontent.com/5941510/77261250-81acde80-6c8d-11ea-8f9a-d11d72797df2.png)

**Additional context**
Please let me know if you need any more info., thanks!!

**Comment by nilsnolde** [comment]
I can reproduce locally with your post. Will dig in quickly.

**Comment by nilsnolde** [comment]
Ooopy, actually quite obvious:

Don't specify the `raw` URL, just the file URL:
https://github.com/eblabs/eblabs_community/blob/master/docs/RetimeTools/README.md

The plugin does that for you:)

**Comment by nilsnolde** [comment]
Great issue reporting btw!! Thanks!

**Comment by eblabs** [comment]
Easy fix, thanks so much @nilsnolde !!
