### ISSUE TITLE
WordPress Warning when plugin is activated

### ISSUE THREAD

**Issue by LuigiBella** [gis-ops/wordpress-markdown-git#12]
**Versions**
Wordpress: 5.4.1
Documents for Git: 1.0.1

**Describe the bug**
Upon activation, the following errors are displayed in WordPress:
Warning: include_once(../../documents-git.php): failed to open stream: No such file or directory in /home/luigibe2/public_html/DAHelpGuide/wp-content/plugins/documents-from-git/includes/providers/class-base-loader.php on line 3

Warning: include_once(): Failed opening '../../documents-git.php' for inclusion (include_path='.:/usr/local/php73/pear') in /home/luigibe2/public_html/DAHelpGuide/wp-content/plugins/documents-from-git/includes/providers/class-base-loader.php on line 3

Warning: Cannot modify header information - headers already sent by (output started at /home/luigibe2/public_html/DAHelpGuide/wp-content/plugins/documents-from-git/includes/providers/class-base-loader.php:3) in /home/luigibe2/public_html/DAHelpGuide/wp-includes/functions.php on line 6221

**Paste the shortcode and the censored contents of config.json**
Contents of `includes/config.json`:
{
  "limit": 5,
  "classes": "",
  "Github": {
    "user": "",
    "token": ""
  },
  "Bitbucket": {
    "user": "",
    "token": ""
  },
  "Gitlab": {
    "user": "",
    "token": ""
  }
}

**To Reproduce**
1. Install Plugin
2. Activate

**Screenshots**
<img width="1767" alt="Screen Shot 2020-04-29 at 11 08 04 PM" src="https://user-images.githubusercontent.com/29728363/80693134-4bbdff80-8a6e-11ea-9cfe-22b595a7e4e7.png">

**Additional context**
This was tested across multiple WordPress installations with repeated results.

Thanks for your time!

**Comment by nilsnolde** [comment]
So sorry I didn't have the time until today to properly catch up on this @LuigiBella! 

I can't reproduce this behavior. Neither with the current `master` nor with the release on the WP Plugin page. I tried with Docker and two images:
- `wordpress:5.3.2-php7.2-apache`
- `wordpress:5.4.1-php7.2-apache` (latest release)

In all 4 situations I can just install the plugin and render any markdown.

I'm not the biggest WP user myself, but do you use multi-sites stuff? Or anything else that's rather special?

**Comment by LuigiBella** [comment]
No problem @nilsnolde ; I appreciate you taking the time to look into this.

The issue is happening on my Siteground hosting account using the latest version of WP(5.4.1) and the Documents from Git plugin from the WP Plugin page, I have tried contacting Siteground but they were unable to provide more information as to a possible cause.

Here is the URL of where the error can be seen: https://dahelpguide.luigibella.com/

Thanks again.

**Comment by nilsnolde** [comment]
Really weird! It's complaining that the file is not where it should be.

What's the structure inside `/home/luigibe2/public_html/DAHelpGuide/wp-content/plugins/documents-from-git/`? E.g. `tree -L 3 /home/luigibe2/public_html/DAHelpGuide/wp-content/plugins/documents-from-git/`?

**Comment by nilsnolde** [comment]
Against all odds: is your provider running Windows servers? I could try changing the path separator to be platform agnostic, didn't really think about anyone using a OS where `/` is not the separator.

**Comment by nilsnolde** [comment]
Hmpf, I got it. Apparently that warning message was there all along, I just didn't realize it.. Just saw the same popping up in phpstorms debug output.

It's a circular reference anyways and apparently it works all the same without. Not sure why it was in there in the first place..

I'll push now some commits, which will close your issues. Forgot to take them to another branch. Can you please give `master` a try with the WP Pusher plugin? And let me know if all works for you now?

**Comment by LuigiBella** [comment]
Thank you Nils!
It is no longer displaying any warnings and my attempt to display a MD file from BitBucket is working.

**Comment by nilsnolde** [comment]
Good to hear!

How about the other issues? Can I close them as well?
