### ISSUE TITLE
Add Jupyter notebooks as document type

### ISSUE THREAD

**Issue by nilsnolde** [gis-ops/wordpress-markdown-git#2]
Could replace the [nbconvert](https://github.com/ghandic/nbconvert) plugin by @ghandic. Let me know in case you're interested in contributing.

**Comment by ghandic** [comment]
I have used nbviewer to render the notebooks, notebooks need to be converted to html from ipynb. If this is incorporated into this repo it could be used

**Comment by nilsnolde** [comment]
Jup, I’d do the same actually here as well. To render the markdown I also send it to githubs rendering endpoint. Should be a quick one to incorporate notebooks via nbviewer and best thing, it’s platform independent.

BTW the whole idea is inspired by your WP plugin. I also „stole“ your checkout link stuff. Reminds me I need to make your contribution more prominent in the README.

**Comment by ghandic** [comment]
Awesome, have you updated the readme?

**Comment by nilsnolde** [comment]
It's what you see right now. If you want to suggest edits, feel free.

**Comment by ghandic** [comment]
Ahh ok, just wondering as you said you need to make the contribution section more prominent
