### ISSUE TITLE
plugin does not respect dark mode

### ISSUE THREAD

**Issue by noah1510** [gis-ops/wordpress-markdown-git#21]
**Versions**
Wordpress: 5.6
Documents for Git: 1.1.0

**Describe the bug**
The text color is not aware of the dark mode (theme twenty-one) and stays black instead of being white (like the default text does)

**Paste the shortcode and the censored contents of config.json**
config.json is the default file with github access token.
`shortcode`

```
[git-github-markdown url="https://github.com/gis-ops/tutorials/blob/master/qgis/QGIS_SimplePlugin.md"]
```

**To Reproduce**
1. Select theme twenty-one
2. Add shortcode
3. turn the dark mode on
4. enjoy not being able to read anything

**Expected behavior**
The text should turn into a bright color to make it readable on a dark background like it does on github.

**Screenshots**
Dark mode on:
![image](https://user-images.githubusercontent.com/14131388/102344420-2d285c80-3f9c-11eb-93f5-4e25e1a53ac3.png)

Dark mode off:
![image](https://user-images.githubusercontent.com/14131388/102344474-3dd8d280-3f9c-11eb-86d3-7d5b14e76e5e.png)

**Comment by nilsnolde** [comment]
Ugh, yeah, that's not really nice. However, I'll pass the cup further down:
https://github.com/sindresorhus/github-markdown-css/issues/76 (who also does the same with another of his projects;))

And I can also only repeat what he's saying: not planning to work on supporting that, as it's not important for us. But PR's will be welcomingly discussed and merged.

**Comment by nilsnolde** [comment]
BTW @noah1510 , there's a tiny fork which should do what you want:
https://github.com/hyrious/github-markdown-css

If you replace this file https://github.com/gis-ops/wordpress-markdown-git/blob/master/documents-git/css/github-markdown.css with the one from the fork, it _might_ just work! 

If you try it out, please leave feedback here. Then I can just test from my side if it doesn't screw up our case and merge.

**Comment by noah1510** [comment]
I just tried using the fork and everything looked exactly the same.
I guess that could be expected, since the fork only adds support for dark mode and does not change any of the old style.
So in addition to using the fork, there need to be some changes on the plugin to select the dark mode classes when wordpress uses  the dark mode.

**Comment by nilsnolde** [comment]
This got merged finally upstream: https://github.com/sindresorhus/github-markdown-css/issues/76

I tried to find out how WP toggles dark mode, but it seems to be theme-specific. I couldn’t find any sort of API in WP that toggles it. We can’t solve theme-specific stuff here I’m afraid..
