### ISSUE TITLE
WP plugin taking too long

### ISSUE THREAD

**Issue by Ryojikn** [gis-ops/wordpress-markdown-git#24]
I'm currently using Documents from Git version 1.1.0, Wordpress 5.6.2 hosted on personal hosting platform, and tried to post
jupyter nbs using the same command as: "[git-github-jupyter url="https://github.com/GIScience/openrouteservice-examples/blob/master/python/ortools_pubcrawl.ipynb"]"

However, page is still blank and seems to be not loading content, the post stays blank
Does it take a lot of time to load? Something like 24 hours.

How could I solve this problem? Any idea?

Post sample:
![image](https://user-images.githubusercontent.com/4712257/110345676-9b197880-800d-11eb-9dab-da47482aa07d.png)

**Comment by nilsnolde** [comment]
No, it's not taking any time at all actually. Guess yours might be in a private repo? If so, check that you've set up the plugin correctly with the credentials for your Git platform. If not, please share the exact URL and I'll try myself.

FWIW, the example still works fine for me:
https://gis-ops.com/test/

**Comment by nilsnolde** [comment]
Ah, and we're running 5.2.9 still, but I think I checked the plugin until 5.4 or smth. It's possible that something breaks on higher versions.. Can you also try a normal markdown, e.g. 
[git-github-markdown url="https://github.com/gis-ops/tutorials/blob/master/general/foss_routing_engines_overview.md"]

If that doesn't work for you, I'll have to dig in soon..

**Comment by Ryojikn** [comment]
This is the post: https://arkbot.com.br/2021/03/deteccao-de-voz-ativa/
Contains the following git reference code:
`[git-github-jupyter url=https://github.com/Ryojikn/speech_study/blob/main/vad/Detecção%20de%20voz%20ativa.ipynb]`

This is another one that I've done in the past: https://arkbot.com.br/2020/08/compressao-de-imagens/
Code used back then:
`[git-github-jupyter url=https://github.com/Ryojikn/computer_vision/blob/master/01%20-%20Image%20processing/Compressão%20de%20imagens.ipynb]`


Only difference between then is that the newer, I pushed to my git yesterday.

Markdown test seems to be working: https://arkbot.com.br/2021/03/test-markdown/

**Comment by Ryojikn** [comment]
So, after a few digging, I finally discovered the problem.

There's a problem with nbviewer related to the new default branch in github as "main".
After I've manually renamed to master, it started to work and render properly as can be seen in: https://arkbot.com.br/2021/03/deteccao-de-voz-ativa/

Link to the issue in nbviewer: https://github.com/jupyter/nbviewer/issues/962

**Comment by nilsnolde** [comment]
Great! And shame on you nbviewer;)
