### ISSUE TITLE
Anchor links to headers don't work

### ISSUE THREAD

**Issue by OskarSwierad** [gis-ops/wordpress-markdown-git#28]
**Versions**
Wordpress: 5.7
Documents for Git: 1.1.1

**Describe the bug**

Links within the page (e.g. `https://example.com/#chapter2`) don't scroll the page to the destination. It seems that `name=""` attribute is missing within the `<a>` tag.
It also breaks GitHub-compatible table of contents.

**Paste the shortcode and the censored contents of config.json**

```
{
  "limit": 5,
  "cache_strategy": "static",
  "cache_ttl": 600,
  "classes": "",
  "Github": {
    "user": XXX,
    "token": XXX
  },
  "Bitbucket": {
    "user": "",
    "token": ""
  },
  "Gitlab": {
    "user": "",
    "token": ""
  }
}
```

**To Reproduce**
1. Visit https://gis-ops.com/qgis-3-plugin-tutorial-geocoding-with-nominatim-part-2/#recommendations
2. Observe it stays at the top of the page. It should jump to the destination (e.g. "Recommendations" paragraph)
3. Visit https://techartaid.com/cheatsheet/
4. Click on links in Table of Contents. Observe it doesn't follow to the paragraph
5. Visit the same page on GitHub, observe it works OK: https://github.com/OskarSwierad/game-art-cheatsheet

**Comment by nilsnolde** [comment]
Yeah, this is the fault of Github's weird Markdown rendering (this plugin gets the HTML from Github's `/markdown` endpoint).. There would probably be a solution one could do in the code, but I wouldn't dig into it. 

Github does give you a link you can use, it's just now what you'd expect. Inspect one of your rendered headings:
![image](https://user-images.githubusercontent.com/25637358/114150038-dc0df100-991b-11eb-8ef6-037af29eecd5.png)

So, the `id` here is not `content-troubleshooting` (as you'd expect) but `user-content-content-troubleshooting`. Try https://techartaid.com/cheatsheet/#user-content-content-troubleshooting and it'll work. 

Unfortunately, if you decide to host your markdown files on WP with this plugin, you'll have to edit your markdowns quite a bit (see also #15) and some of the edits will make it unusable with other markdown renderers. Or you'll rely more on raw HTML, which will work in all situations, but who really wants that;)
