### ISSUE TITLE
Inline codeblocks not working correctly?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [gis-ops/wordpress-markdown-git#40]
**Versions**
Wordpress: 5.9.3
Documents for Git:  2.2.0

**Describe the bug**
It seems that any inline code is converted to a full code block (or at least on my website). This means this:

#### - 0.1.5
  - Fixes `TableOfContent.Update()`

#### - 0.1.4 - 2022.04.03
  - First official release

Is translated as:

![image](https://user-images.githubusercontent.com/15063294/166154808-a6af8dbd-0336-4ea8-bbd9-916a52507056.png)

It can be seen here: https://evotec.xyz/docs/officeimo-release-history/

**Paste the shortcode and the censored contents of config.json**

`shortcode`

I have no config.json there. Configured only via GUI

**To Reproduce**
1. Create MD with inline code
3. Notice it converts inline code to a full code block

**Expected behavior**

It should just "highlight" the code (more of bold or something)

**Screenshots**

**Additional context**

**Comment by nilsnolde** [comment]
that's not the plugin doing that.. see a quick test here: https://gis-ops.com/test/

**Comment by PrzemyslawKlys** [comment]
YE, i noticed on another page it working properly. Something is wrong on that specific page. Thank you
